version: '3'
services:
  # Serviço do NGINX (proxy reverso)
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Mapeia a porta 80 do container para a porta 80 do host
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf  # Arquivo de configuração do NGINX
    depends_on:
      - server
      - web
  
  # Serviço do front-end (Vite com TypeScript)
  web:
    build:
      context: ./web  # Diretório onde está o código do front-end (o diretório que contém o Dockerfile)
    expose:
      - "80"  # Porta interna do front-end
    networks:
      - app_network  # Adiciona o container à rede compartilhada
  
  # Serviço do back-end (Node.js com API)
  server:
    build:
      context: ./server  # Diretório onde está o código do back-end
    expose:
      - "3020"  # Porta interna do back-end
    environment:
      - NODE_ENV=production
    networks:
      - app_network  # Adiciona o container à rede compartilhada
  
networks:
  app_network:
    driver: bridge
