services:
  server:
    build: .
    image: monitoramento-geres-v-0.1
    container_name: monitoramento-geres
    ports:
      - "3020:3020"
    volumes:
      - ./prisma:/usr/src/app/prisma
    environment:
      - EMAIL_USER="silvaugusto222@gmail.com"
      - EMAIL_PASS="cyri ayau hcro cszn "
    restart: always