services:
  server:
    build: .
    image: monitoramento-geres-v-0.1
    container_name: monitoramento-geres
    ports:
      - "3020:3020"
    volumes:
      - ./prisma:/usr/src/app/prisma
    restart: always
